### ISSUE TITLE
[Bug] Examining non-existent mailbox

### ISSUE THREAD

**Issue by EpicEricEE** [bkaankose/Wino-Mail#366]
My university's mail server seems to list mailboxes that are not meant to be examined (see `\Noselect` flag in the response to the `LIST` command), leading to an error when trying to add the account.

**Additional context:**
In the logs, I have found the following relevant information:

_Protocol log_
```
C: A00000006 ENABLE QRESYNC CONDSTORE
S: * ENABLED CONDSTORE QRESYNC
S: A00000006 OK Completed
C: A00000007 LIST "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Noselect) "/" "Mailspring"
S: A00000007 OK Completed (0.000 secs)
C: A00000008 EXAMINE Mailspring (CONDSTORE)
S: A00000008 NO Mailbox does not exist
```

_Server log:_
```
2024-09-12 13:32:14.852 +02:00 [ERR] Synchronizing IMAP folders failed.
MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'EXAMINE' command with a 'NO' response: Mailbox does not exist
   at MailKit.Net.Imap.ImapCommand.ThrowIfNotOk(String command)
   at MailKit.Net.Imap.ImapFolder.ProcessOpenResponse(ImapCommand ic, FolderAccess access)
   at MailKit.Net.Imap.ImapFolder.OpenAsync(ImapCommand ic, FolderAccess access)
   at Wino.Core.Synchronizers.ImapSynchronizer.SynchronizeFoldersAsync(CancellationToken cancellationToken)
```

_Client log:_
```
2024-09-12 13:32:14.187 +02:00 [INF] Server connection established successfully.
2024-09-12 13:32:14.923 +02:00 [ERR] AccountCreation
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wino.Mail.ViewModels.AccountManagementViewModel.<AddNewAccountAsync>d__32.MoveNext() + 0x580
```

**Comment by bkaankose** [comment]
This should be fixed with the latest v1.10.2. Closing as fixed. Please re-open if you encounter the same issue still.
