### ISSUE TITLE
[Bug] Syntax error in BODYSTRUCTURE. Unexpected atom token: 3.45027e+06

### ISSUE THREAD

**Issue by f242** [bkaankose/Wino-Mail#469]
Have an error popup while program tries to sync mail
v1.9.30.0 & win 10 x64 22h2
 
```
2024-11-06 03:44:41.450 +03:00 [INF] Internal synchronization started for Моя почта
2024-11-06 03:44:41.489 +03:00 [INF] Options: Type: Full, Folders: None
2024-11-06 03:44:51.525 +03:00 [ERR] Synchronization failed for Моя почта
MailKit.Net.Imap.ImapProtocolException: Syntax error in BODYSTRUCTURE. Unexpected atom token: 3.45027e+06
   at MailKit.Net.Imap.ImapEngine.ParseNumber(ImapToken token, Boolean nonZero, String format, Object[] args)
   at MailKit.Net.Imap.ImapUtils.ParseNumberToken(ImapToken token, String format)
   at MailKit.Net.Imap.ImapUtils.ReadNumberAsync(ImapEngine engine, String format, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseBodyAsync(ImapEngine engine, String format, String path, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseMultipartAsync(ImapEngine engine, String format, String path, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseBodyAsync(ImapEngine engine, String format, String path, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.ParseSummaryItemsAsync(ImapEngine engine, MessageSummary message, FetchSummaryItemsCompletedCallback completed, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponseAsync(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync()
   at MailKit.Net.Imap.ImapEngine.IterateAsync()
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic)
   at MailKit.Net.Imap.ImapFolder.FetchAsync(IList`1 uids, IFetchRequest request, CancellationToken cancellationToken)
   at Wino.Core.Synchronizers.ImapSynchronizer.SynchronizeFolderInternalAsync(MailItemFolder folder, CancellationToken cancellationToken)
   at Wino.Core.Synchronizers.ImapSynchronizer.SynchronizeFolderInternalAsync(MailItemFolder folder, CancellationToken cancellationToken)
   at Wino.Core.Synchronizers.ImapSynchronizer.SynchronizeInternalAsync(SynchronizationOptions options, CancellationToken cancellationToken)
   at Wino.Core.Synchronizers.BaseSynchronizer`2.SynchronizeAsync(SynchronizationOptions options, CancellationToken cancellationToken)

```

**Comment by jstedfast** [comment]
This is a bug in mail.ru's IMAP implementation that is decimal numbers with exponents instead of integer values for body part sizes

**Comment by f242** [comment]
> This is a bug in mail.ru's IMAP implementation that is decimal numbers with exponents instead of integer values for body part sizes

Despite this, Thunderbird and Outlook as well as Mail and Calendar work correctly🤔

**Comment by bkaankose** [comment]
> This is a bug in mail.ru's IMAP implementation that is decimal numbers with exponents instead of integer values for body part sizes

Is there anything possible to interfere with this behavior in Mailkit?

**Comment by jstedfast** [comment]
I would prefer to see mail.rubric the issue.

And yes, I'm here. Randomly saw this project was using MailKit and am pretty excited that someone is using it to create an email client 😁

Very cool.

**Comment by bkaankose** [comment]
> I would prefer to see mail.ru fix the issue, but I would consider a workaround if not.
> 
> And yes, I'm here. Randomly saw this project was using MailKit and am pretty excited that someone is using it to create an email client 😁
> 
> Very cool.

Super exited that Wino got your attention! All synchronizers leverage MimeKit and specially ImapSynchronizer uses MailKit extensively. I'm pretty sure the current implementation of Wino's imap synchronizer is not the best, and probably I did some parts very weird. If you have suggestions or tips/tricks to make the imap synchronization better you can always reach out to me. I will gladly make the required changes in the code along with your expertise.

Mailkit synchronization call for imap happens here:
https://github.com/bkaankose/Wino-Mail/blob/8367efa1749b056465321dc7ac5f91e1952f3be9/Wino.Core/Synchronizers/Mail/ImapSynchronizer.cs#L766

**Comment by jstedfast** [comment]
Forgot to comment that I added a work-around for this: https://github.com/jstedfast/MailKit/issues/1838

Will be in the v4.9.0 release when I push it out. Currently blocking on some new S/MIME functionality in MimeKit that needs confirmation that it works before I can merge & make a release.

Will update you when I push it.

**Comment by jstedfast** [comment]
Looks like I forgot to notify you guys that 4.9.0 was released.

**Comment by bkaankose** [comment]
1.9.40 is live and should have this fix. Please try again and let me know.

**Comment by f242** [comment]
> let me know.

all fine!
