### ISSUE TITLE
[Bug] Can't synchronize Outlook, can't add Outlook account

### ISSUE THREAD

**Issue by blablabla123455** [bkaankose/Wino-Mail#480]
My Outlook account didn't synchronize due to error (Wino Server):
```
2024-11-25 14:38:10.362 +01:00 [ERR] Synchronizing folders for Outlook
Status Code: 503
Microsoft.Graph.ServiceException: generalException
   at Microsoft.Graph.ResponseHandler`1.ValidateSuccessfulResponse(HttpResponseMessage httpResponseMessage, Dictionary`2 errorMapping)
   at Microsoft.Graph.ResponseHandler`1.HandleResponseAsync[NativeResponseType,ModelType](NativeResponseType response, Dictionary`2 errorMappings)
   at Microsoft.Graph.BatchResponseContent.GetResponseByIdAsync[T](String requestId, IResponseHandler responseHandler)
   at Wino.Core.Synchronizers.OutlookSynchronizer.SynchronizeFoldersAsync(CancellationToken cancellationToken)
   at Wino.Core.Synchronizers.OutlookSynchronizer.SynchronizeInternalAsync(SynchronizationOptions options, CancellationToken cancellationToken)
2024-11-25 14:38:10.363 +01:00 [ERR] Synchronization failed for Outlook
```

I tried multiple times, the same error was happening. I thought re-adding account will help, but I can't add Outlook account either, due to error (Wino Server):
```
2024-11-25 14:45:35.101 +01:00 [ERR] Failed to update profile information for Outlook
Microsoft.Graph.Models.ODataErrors.ODataError: Internal Server Error
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.MeRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at Wino.Core.Synchronizers.OutlookSynchronizer.GetSenderNameAsync()
   at Wino.Core.Synchronizers.OutlookSynchronizer.GetProfileInformationAsync()
   at Wino.Core.Synchronizers.BaseSynchronizer`2.SynchronizeProfileInformationInternalAsync()
   at Wino.Core.Synchronizers.BaseSynchronizer`2.SynchronizeAsync(SynchronizationOptions options, CancellationToken cancellationToken)
```

I also tried uninstalling Wino completely and I installed again, but that didn't help either.

**Comment by blablabla123455** [comment]
Looks like Outlook itself has some problems: https://www.windowscentral.com/software-apps/microsoft-365-outlook-and-microsoft-teams-are-down-heres-when-youll-be-able-to-use-them-again

**Comment by blablabla123455** [comment]
Hmmm, new Outlook app works properly (it had some issues with loading mails but now it seems fine) but I still can't even create an Outlook account in Wino due to the error I mentioned earlier.
