### ISSUE TITLE
翻译，内置浏览器以及崩溃问题。| Translations, built-in browsers, and crash issues.

### ISSUE THREAD

**Issue by AnnualfireCHW** [bkaankose/Wino-Mail#484]
1、选择语言界面使用目标语言，例如，简体中文，“**简体中文**”；英语“**English**”，法语““**Français**”
![image](https://github.com/user-attachments/assets/447db1e9-47f5-4033-9d08-34c7c8707cbb)
2、重命名文件夹时，软件会崩溃退出。
![image](https://github.com/user-attachments/assets/d16959cb-d239-4aef-8aa4-bfde423ae028)
3、软件貌似捆绑了一个Microsoft Edge导致体积增大，并且还会导致汉化不完整。建议调用内置edge或者webview

机器翻译：
1. Select the language interface to use the target language, for example, Chinese Simplified, "**简体中文**"; English "**English**", French "**Français**"
! [image] (https://github.com/user-attachments/assets/447db1e9-47f5-4033-9d08-34c7c8707cbb)
2. When renaming a folder, the software will crash and exit.
! [image] (https://github.com/user-attachments/assets/d16959cb-d239-4aef-8aa4-bfde423ae028)
3. The software seems to be bundled with a Microsoft Edge, resulting in an increase in size, and it will also lead to incomplete sinicization. It is recommended to call the built-in edge or webview
4. Since I only speak a little English, I use a translator to communicate if there is an offensive or incorrect expression. Please inform me that this is an issue with the translator. ...

**Comment by AnnualfireCHW** [comment]
![image](https://github.com/user-attachments/assets/4239453a-ae25-435a-8aab-8b5332254207)

**Comment by chenseanxy** [comment]
2 confirmed: any folder rename operation throws such exception
```
System.NotSupportedException
  HResult=0x80131515
  Message=Deserialization of interface types is not supported. Type 'Wino.Core.Domain.Models.Folders.IMailItemFolder'. Path: $.MailItemFolder | LineNumber: 0 | BytePositionInLine: 19.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Wino.Core.UWP.Services.WinoServerConnectionManager.HandleUIMessage(String messageJson, String typeName) in C:\Users\User\source\repos\Wino-Mail\Wino.Core.UWP\Services\WinoServerConnectionManager.cs:line 233
   at Wino.Core.UWP.Services.WinoServerConnectionManager.ServerMessageReceived(AppServiceConnection sender, AppServiceRequestReceivedEventArgs args) in C:\Users\User\source\repos\Wino-Mail\Wino.Core.UWP\Services\WinoServerConnectionManager.cs:line 185

Inner Exception 1:
NotSupportedException: Deserialization of interface types is not supported. Type 'Wino.Core.Domain.Models.Folders.IMailItemFolder'.
```

3 I think issue is mainly that webview defaults to English no matter the languages set in the app. https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/webview-features-flags?tabs=dotnetcsharp

**Comment by bkaankose** [comment]
1) This is great idea, I'll do it thanks!
2) It's fixed in the main branch for the next update.
3) It's WebView2. Not sure if end users need to use this functionality as some functionality like 'save as' is misleading. I'll try to disable context menu.

**Comment by AnnualfireCHW** [comment]
> 1. This is great idea, I'll do it thanks!
> 2. It's fixed in the main branch for the next update.
> 3. It's WebView2. Not sure if end users need to use this functionality as some functionality like 'save as' is misleading. I'll try to disable context menu.

很荣幸能为这个软件添砖加瓦。献出自己的一份力，并且得到了作者的支持与肯定。
至于您提到的“右键菜单”，我个人认为可以保留复制按钮，也可以加入批注标识等内容（不过这并非主要，有余力时尝试）
至于菜单的按钮，最好是目标语言，防止误导。
再次感谢开发者愿意倾听意见，一起让这个项目变得越来越好，对于之后的情况，我静候佳音:)

It's an honor to contribute to this software. contributed his own strength, and got the support and affirmation of the author.
As for the "right-click menu" you mentioned, I personally think you can keep the copy button, and you can also add annotation logos and so on (but this is not the main thing, try when you have the time)
As for the buttons of the menu, it is better to be in the target language to prevent misleading.
Thanks again to the developers for their willingness to listen and work together to make this project better and better, and I'm waiting for good news :)

**Comment by AnnualfireCHW** [comment]
> 2 confirmed: any folder rename operation throws such exception
> 
> ```
> System.NotSupportedException
>   HResult=0x80131515
>   Message=Deserialization of interface types is not supported. Type 'Wino.Core.Domain.Models.Folders.IMailItemFolder'. Path: $.MailItemFolder | LineNumber: 0 | BytePositionInLine: 19.
>   Source=System.Text.Json
>   StackTrace:
>    at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
>    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
>    at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
>    at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
>    at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
>    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
>    at Wino.Core.UWP.Services.WinoServerConnectionManager.HandleUIMessage(String messageJson, String typeName) in C:\Users\User\source\repos\Wino-Mail\Wino.Core.UWP\Services\WinoServerConnectionManager.cs:line 233
>    at Wino.Core.UWP.Services.WinoServerConnectionManager.ServerMessageReceived(AppServiceConnection sender, AppServiceRequestReceivedEventArgs args) in C:\Users\User\source\repos\Wino-Mail\Wino.Core.UWP\Services\WinoServerConnectionManager.cs:line 185
> 
> Inner Exception 1:
> NotSupportedException: Deserialization of interface types is not supported. Type 'Wino.Core.Domain.Models.Folders.IMailItemFolder'.
> ```
> 
> 3 I think issue is mainly that webview defaults to English no matter the languages set in the app. Should be fixable by setting the flag at lanuch. https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/webview-features-flags?tabs=dotnetcsharp`lang`

great idea
